using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;
using System.Drawing;
using System.Threading.Tasks;
using Water4ENBwatercolor.Settings;


namespace Water4ENBwatercolor
{

    public class Program
    {
        // Settings holder for older Synthesis versions
        //private static PatcherSettings? _settings;
        private static Lazy<Settings.Settings> _settings = null!;

        // "Natural Shades of Skyrim" colors
        private static readonly Color NaturalSunrise = Color.FromArgb(137, 160, 171);
        private static readonly Color NaturalDay = Color.FromArgb(175, 216, 237);
        private static readonly Color NaturalSunset = Color.FromArgb(105, 142, 154);
        private static readonly Color NaturalNight = Color.FromArgb(31, 63, 75);

        // "Shades of Skyrim" colors 
        private static readonly Color ShadesSunrise = Color.FromArgb(154, 154, 154);
        private static readonly Color ShadesDay = Color.FromArgb(210, 210, 210);
        private static readonly Color ShadesSunset = Color.FromArgb(138, 138, 138);
        private static readonly Color ShadesNight = Color.FromArgb(60, 60, 60);


        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "WaterColorPatcher.esp")
                .Run(args);
        }


        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {

            Color targetSunrise, targetDay, targetSunset, targetNight;
            if (_settings.Value.NaturalShadesOfSkyrim)
            {
                targetSunrise = NaturalSunrise;
                targetDay = NaturalDay;
                targetSunset = NaturalSunset;
                targetNight = NaturalNight;
            }
            else
            {
                targetSunrise = ShadesSunrise;
                targetDay = ShadesDay;
                targetSunset = ShadesSunset;
                targetNight = ShadesNight;
            }

            int patchedCount = 0;

            foreach (var weatherGetter in state.LoadOrder.PriorityOrder.Weather().WinningOverrides())
            {
                var weather = state.PatchMod.Weathers.GetOrAddAsOverride(weatherGetter);
                weather.WaterMultiplierColor.Sunrise = targetSunrise;
                weather.WaterMultiplierColor.Day = targetDay;
                weather.WaterMultiplierColor.Sunset = targetSunset;
                weather.WaterMultiplierColor.Night = targetNight;

                patchedCount++;
            }

            System.Console.WriteLine($"Successfully patched {patchedCount} records with NaturalShadesOfSkyrim {_settings.Value.NaturalShadesOfSkyrim}.");
        }
    }
}